outcome: outcomes/HEA_Anti-depressive
n_tokens: 450000 #srv 9 #bg: 200000 #full: 800000 #labour: 1500000 #lpr: 150000 #health: 350000 #lpr_lmdb: 700000
auto_ntokens: False
# HEA   full: 1100000   lpr: 400000   lpr_amrun: 
load_pretrained_model: destiny-pretrain/001_expensive_lynx-pretrain-destiny_dataset/best.ckpt
# load_pretrained_model: destiny-pretrain/009_genuine_bison-pretrain-destiny_dataset_bg/best.ckpt
# checkpoint: null
dir_path: destiny_dataset
# Model info
d_model: 256
num_heads: 4
num_layers: 4
dropout: 0.1
bias: False
# Optimizer info
beta1: 0.9
beta2: 0.999
weight_decay: 0.1
learning_rate: 0.00003 #0.00003 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
warmup_steps: 0
warmup_epochs: 2
# Dataloading info
num_workers: 20
max_seq_len: 8192
# Some additional info
max_epochs: 50
precision: 16-mixed
float32_matmul_precision: medium
# Data config
subset_background: False
experiment_name: destiny-finetune2010
lengths: lengths
source_dir: destiny
background: background
cohorts:
  train: cohort/train
  val: cohort/val
  # test: cohort/test
prediction_windows:
  - 1000
pred_times:
  - "-10y"
  - "-5y"
  - "-3y"
  - "-1y"
sources: []
  # # Demographics
  # - address_change
  # - bef_updates
  # - family_births_deaths
  # - marital_status
  # - migration
  # # Labour & income
  # - akm
  # - amrun
  # - ind
  # # Health
  # - lmdb
  # - lpr
  # - sygesik
  # # Education
  # - primary_school_grades
  # - high_school_grades
  # - higher_ed_grades
  # - enrollment
  # - graduation
  # - diploma_grades
  # - qualifications
  # - wellbeing
  # - national_tests
  # - absences
  # # Social conditions
  # - decisions
  # - charges
  # - conferred_charges
  # - minor_charges
  # - victims
  # - jail_parole_start
  # - jail_end
  # - parole_end
  # - out_of_home_placements
  # - drug_treatment_start
  # - drug_treatment_end
  # - preventative_measures_start
  # - preventative_measures_end