background: background
beta1: 0.9
beta2: 0.999
bias: false
cls_token: false
d_model: 32
dir_path: destiny_test_dataset_timetoken_
dropout: 0.1
experiment_name: destiny_test
float32_matmul_precision: medium
learning_rate: 0.2
lengths: lengths
masking_ratio: 0.15
max_epochs: 1
max_seq_len: 26000
n_tokens: 80000
num_heads: 4
num_layers: 6
num_workers: 4
precision: 16-mixed
pretrain_style: AR
segment: true
sep_token: false
source_dir: destiny_test
sources:
- address_change
- bef_updates
- family_births_deaths
- marital_status
- migration
- akm
- amrun
- ind
- lmdb
- lpr
- sygesik
- primary_school_grades
- high_school_grades
- higher_ed_grades
- enrollment
- graduation
- diploma_grades
- qualifications
- wellbeing
- national_tests
- absences
- decisions
- charges
- conferred_charges
- minor_charges
- victims
- jail_parole_start
- jail_end
- parole_end
- out_of_home_placements
- drug_treatment_start
- drug_treatment_end
- preventative_measures_start
- preventative_measures_end
subset_background: false
swiglu: false
time_encoding: time_tokens
enable_logging: true
warmup_steps: 50000
weight_decay: 0.1
